version: '3'
services:
    db:
      image: mysql
      ports:
        - 3306:3306
      environment:
            MYSQL_ROOT_PASSWORD: abc1234

    myadmin:
      image: phpmyadmin
      ports:
        - 8888:80

    web:
      image: tutum/apache-php
      ports:
        - 8080:80
      volumes:
        - $PWD:/var/www/html
